monsieurbiz_sylius_cms_admin_modal_form:
    path: /monsieurbiz_sylius_cms/modal/edit
    methods: [GET]
    defaults:
        _controller: Monsieurbiz\SyliusCmsPlugin\Controller\ModalController:formAction

monsieurbiz_sylius_cms_admin_modal_submit:
    path: /monsieurbiz_sylius_cms/modal/submit
    methods: [POST]
    defaults:
        _controller: Monsieurbiz\SyliusCmsPlugin\Controller\ModalController:submitAction
