monsieur_biz_sylius_cms_admin_modal_form:
    path: /monsieur_biz_sylius_cms/modal/edit
    methods: [GET]
    defaults:
        _controller: MonsieurBiz\SyliusCmsPlugin\Controller\ModalController:formAction

monsieur_biz_sylius_cms_admin_modal_submit:
    path: /monsieur_biz_sylius_cms/modal/submit
    methods: [POST]
    defaults:
        _controller: MonsieurBiz\SyliusCmsPlugin\Controller\ModalController:submitAction
