sylius_ui:
    events:
        sylius.admin.layout.javascripts:
            blocks:
                monsieurbiz_richeditor_init_app:
                    template: '@MonsieurBizSyliusRichEditorPlugin/Admin/app.html.twig'
