imports:
  - { resource: "services.yaml" }

monsieur_biz_sylius_rich_editor:
  upload_directory: '%kernel.project_dir%/public/media/rich-editor'

sylius_resource:
  resources:
    monsieur_biz_sylius_rich_editor.product:
      classes:
        model: '%sylius.model.product.class%'
        repository: MonsieurBiz\SyliusRichEditorPlugin\Repository\ProductRepository

#sylius_ui:
#    events:
#        sylius.admin.layout.javascripts:
#            blocks:
#                monsieurbiz_rich_editor_app:
#                    template: '@MonsieurBizSyliusRichEditorPlugin/Admin/app.html.twig'
                    
