imports:
  - { resource: "services.yaml" }

monsieur_biz_sylius_cms:
  # @TODO : Check if we can improve it
  ui_element_classes :
    - 'MonsieurBiz\SyliusCmsPlugin\UiElement\Image'
    - 'MonsieurBiz\SyliusCmsPlugin\UiElement\Quote'
    - 'MonsieurBiz\SyliusCmsPlugin\UiElement\Text'
  upload_directory: '%kernel.project_dir%/public/media/monsieur_biz_sylius_cms'
