services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MonsieurBiz\SyliusRichEditorPlugin\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  MonsieurBiz\SyliusRichEditorPlugin\Twig\:
    resource: '../../Twig'

  # Add JS for plugin
  monsieurbiz_richeditor.block_event_listener.layout.javascripts:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - '@@MonsieurBizSyliusRichEditorPlugin/Shop/js.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.javascripts, method: onBlockEvent }

  monsieurbiz.richeditor.metadata_registry:
    class: MonsieurBiz\SyliusRichEditorPlugin\UiElement\Metadata\Registry

  MonsieurBiz\SyliusRichEditorPlugin\UiElement\Metadata\RegistryInterface: '@monsieurbiz.richeditor.metadata_registry'

  monsieurbiz.richeditor.registry:
    class: MonsieurBiz\SyliusRichEditorPlugin\UiElement\Registry

  MonsieurBiz\SyliusRichEditorPlugin\UiElement\RegistryInterface: '@monsieurbiz.richeditor.registry'

  # File uploader
  MonsieurBiz\SyliusRichEditorPlugin\Service\FileUploader:
    arguments:
      $targetPath: '%monsieurbiz.richeditor.config.upload_directory%'
      $publicDirectory: '%env(DOCUMENT_ROOT)%'
